apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: app-deployment
spec:
  replicas: {{.Values.scale}} # see values.yaml file
  template:
      metadata:
        labels:
          app: app-pod-selector
      spec:
        containers:
          - name: app-pod-container
            image: nginx:{{.Values.tag}} # see values.yaml file
            ports:
              - containerPort: 80
