kind: Service
apiVersion: v1
metadata:
  name: app-service
spec:
  type: ClusterIP
  ports:
    - name: main
      protocol: TCP
      port: 80
      targetPort: 80
  selector:
    app: app-pod-selector
